spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

server:
  port : 8013



#grpc:
#  client:
#      address: soa:9091






#grpc:
#  client:
#      address: static://tura:9091