server:
  port: 8081


spring:
  cloud:
    gateway:
      routes:
        - id: soa
          uri: http://localhost:8011
          predicates:
#            - Path=/users1/api/korisnik/**,/users1/**
            - Path=/users1/**
        - id: soablog
          uri: http://localhost:8012
          predicates:
            - Path=/blogs/**
        - id: tura
          uri: http://localhost:8013
          predicates:
            - Path=/tours/**
#        - id: static3
#          uri: http://tura:8013
#          predicates:
#            - Path=/**
#        - id: soablog
#          uri: http://soablog:8012
#          predicates:
#            - Path=/api/blogovi/**
#        - id: tura
#          uri: http://tura:8013
#          predicates:
#            - Path=/api/ture/**


#      globalcors:
#        cors-configurations:
#          '[0]':
#            allowed-origins: "http://localhost:8011"
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE



#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: containername1
#          uri: http://containername1:containername1port
#          predicates:
#            - Path=/x/y/**
#          metadata:
#            cors:
#              allowedOrigins: "http://localhost:containername1port"
#              allowedMethods:
#                - GET
#                - POST
#                - PUT
#                - DELETE
#                - OPTIONS
#              maxAge: 3600
#
#
#        - id: soablog
#          uri: http://soablog:8012
#          predicates:
#            - Path=/api/blogovi/**