server:
  port: 8081


spring:
  cloud:
    gateway:
      routes:
        - id: soa
          uri: http://soa:8011
          predicates:
#            - Path=/users1/api/korisnik/**,/users1/**
            - Path=/users1/**
        - id: soablog
          uri: http://soablog:8012
          predicates:
            - Path=/blogs/api/blogovi/noviblog,/blogs/api/blogovi/noviblogimages,/blogs/api/blogovi/svi,/blogs/api/blogovi/novikomentar,/blogs/api/blogovi/jedanblog,/blogs/api/blogovi/slikebloga,/blogs/api/blogovi/svikomentari
          filters:
            - AuthenticationFilter

        - id: tura
          uri: http://tura:8013
          predicates:
            - Path=/tours/api/ture/novatura,/tours/api/ture/svekreiraneture
          filters:
            - AuthenticationFilter1

        - id: tura1
          uri: http://tura:8013
          predicates:
            - Path=/tours/api/ture/sve,/tours/api/ture/novakorpa,/tours/api/ture/dodajukorpu,/tours/api/ture/ukloniizkorpe
          filters:
            - AuthenticationFilter2

        - id: turastatic
          uri: http://tura:8013
          predicates:
            - Path=/tours/*.html

        - id: turastatic1
          uri: http://tura:8013
          predicates:
            - Path=/tours/*.js


        - id: blogstatic
          uri: http://soablog:8012
          predicates:
            - Path=/blogs/*.html

        - id: blogstatic1
          uri: http://soablog:8012
          predicates:
            - Path=/blogs/*.js

        - id: blogstatic2
          uri: http://soablog:8012
          predicates:
            - Path=/uploads/*.png








#        - id: tura
#          uri: http://localhost:8013
#          predicates:
#            - Path=/tours/**
#          filters:
#            - AuthenticationFilter













#        - id: static3
#          uri: http://tura:8013
#          predicates:
#            - Path=/**
#        - id: soablog
#          uri: http://soablog:8012
#          predicates:
#            - Path=/api/blogovi/**
#        - id: tura
#          uri: http://tura:8013
#          predicates:
#            - Path=/api/ture/**


#      globalcors:
#        cors-configurations:
#          '[0]':
#            allowed-origins: "http://localhost:8011"
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE



#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: containername1
#          uri: http://containername1:containername1port
#          predicates:
#            - Path=/x/y/**
#          metadata:
#            cors:
#              allowedOrigins: "http://localhost:containername1port"
#              allowedMethods:
#                - GET
#                - POST
#                - PUT
#                - DELETE
#                - OPTIONS
#              maxAge: 3600
#
#
#        - id: soablog
#          uri: http://soablog:8012
#          predicates:
#            - Path=/api/blogovi/**